{% set processor = 'cpu' if cookiecutter.processor == "CPU" else 'gpu' %}
{% set libraries = 'min' if cookiecutter.libraries == "Minimal" else 'full' %}
{% set cuda_version = '/10' if (cookiecutter.cuda == "10") and (cookiecutter.processor == "GPU") else '' %}
{% set cuda_version = '/92' if (cookiecutter.cuda == "9.2") and (cookiecutter.processor == "GPU") else cuda_version %}
{% set cuda_version = '/90' if (cookiecutter.cuda == "9.0") and (cookiecutter.processor == "GPU") else cuda_version %}
{% set volume = './:/mnt' if cookiecutter.processor == "CPU" else './:/root' %}
version: '{{ '3' if cookiecutter.processor == "CPU" else '2.3' }}'
services:
    ntbk-{{ processor }}-{{ cookiecutter.project_name.lower().replace(' ', '_') }}:  
      image: img_{{ processor }}_{{ libraries }}-{{ cookiecutter.project_name.lower().replace(' ', '_') }}:{{ cookiecutter.username.lower().replace(' ', '_') }}
      container_name: cntnr_{{ processor }}_{{ libraries }}-{{ cookiecutter.project_name.lower().replace(' ', '_') }}-{{ cookiecutter.username.lower().replace(' ', '_') }}
      build: docker/{{ processor }}/{{ libraries }}{{ cuda_version }}
      volumes:
         - {{ volume }}
      # Here Cookiecutter will try to append based on CPU or GPU
      {%- if cookiecutter.processor == "CPU" -%}
      # Entry Point for CPU
      entrypoint: bash -c "cd /mnt && jupyter notebook --NotebookApp.token='{{ cookiecutter.password }}' --ip=0.0.0.0 --allow-root && /bin/bash"
      {% endif %}
      {%- if cookiecutter.processor == "GPU" -%}
      # Runtime for GPU
      runtime: nvidia
      ipc: host
      cpuset: "29-55"
      mem_limit: 64g
      command: jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='{{ cookiecutter.password }}' --notebook-dir='/root'
      {% endif %}
      ports:
         - "0.0.0.0:{{ cookiecutter.port }}:8888"
      stdin_open: true
      tty: true
