version: '3'
services:
   notebook-server:
      image: notebook_image-{{cookiecutter.project_name}}
      container_name: notebook_container-{{cookiecutter.project_name}}
      build: .
      ports:
         - "0.0.0.0::8888"
      volumes:
         - ./:/mnt
      entrypoint: bash -c "cd /mnt && jupyter notebook --NotebookApp.token='' --ip=* --allow-root && /bin/bash"
      stdin_open: true
      tty: true

