{%- if cookiecutter.processor == "CPU" -%}
version: '3'
services:
   notebook-cpu-server:
      image: notebook_cpu_image:{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      container_name: cpu_container-{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      build: docker/cpu
      ports:
         - "0.0.0.0:8870:8888"
      volumes:
         - ./:/mnt
      entrypoint: bash -c "cd /mnt && jupyter notebook --NotebookApp.token='1234r' --ip=0.0.0.0 --allow-root && /bin/bash"
      stdin_open: true
      tty: true
{%- elif cookiecutter.processor == "Cuda10" -%}
version: '2.3'
services:
   notebook-gpu-server:
      image: notebook_gpu_image:{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      container_name: gpu_container-{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      build: docker/gpu_cuda10_cudnn7_devel_ubuntu1804
      runtime: nvidia
      ports:
         - "0.0.0.0:8081:8888"
      volumes:
         - ./:/root
      ipc: host
      command: jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/root'
      stdin_open: true
      tty: true
{%- elif cookiecutter.processor == "Cuda92" -%}
version: '2.3'
services:
   notebook-gpu-server:
      image: notebook_gpu_image:{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      container_name: gpu_container-{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      build: docker/gpu_cuda92_cudnn7_devel_ubuntu1804
      runtime: nvidia
      ports:
         - "0.0.0.0:8081:8888"
      volumes:
         - ./:/root
      ipc: host
      command: jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/root'
      stdin_open: true
      tty: true
{% endif %}